- name: Primer Play
  hosts: all 
  tasks:
    - name: Instalar VIM
      yum: 
        name: vim
        state: latest
    - include: instalar_apache2.yml
- name: Segundo Play
  include: segundoPlayInclude.yml
