- name: Crear Ficheros usando variables
  hosts: localhost
  connection: local
  vars:
    - miip: "1.1.1.1"
  tasks:
    - name: Crear ficheros con variables
      template: 
        src: plantillas/hosts.j2
        dest: /tmp/hosts
